# Generated by Django 2.2.6 on 2019-11-13 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='satus',
            new_name='status',
        ),
    ]
