# Generated by Django 2.2.6 on 2019-11-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyApp', '0002_auto_20191113_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='finished',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='started',
            field=models.DateTimeField(blank=True),
        ),
    ]
