# Generated by Django 2.2.6 on 2019-11-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyApp', '0003_auto_20191113_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
