# Generated by Django 2.2.6 on 2019-12-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummyApp', '0004_auto_20191113_0107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserB',
        ),
    ]
